package engine

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/richardwooding/gitlapse/internal/history"
)

func commitsN(n int) []history.Commit {
	out := make([]history.Commit, n)
	for i := range out {
		out[i] = history.Commit{SHA: string(rune('a' + i%26)), Time: time.Unix(int64(i), 0)}
	}
	return out
}

func TestSampleKeepsAllWhenUnderMax(t *testing.T) {
	c := commitsN(10)
	got := Sample(c, 20)
	if len(got) != 10 {
		t.Fatalf("got %d commits, want 10", len(got))
	}
}

func TestSampleKeepsEndpoints(t *testing.T) {
	c := commitsN(1000)
	got := Sample(c, 240)
	if len(got) != 240 {
		t.Fatalf("got %d commits, want 240", len(got))
	}
	if got[0] != c[0] {
		t.Errorf("first sampled commit is not the first commit")
	}
	if got[len(got)-1] != c[len(c)-1] {
		t.Errorf("last sampled commit is not the last commit")
	}
	for i := 1; i < len(got); i++ {
		if !got[i].Time.After(got[i-1].Time) {
			t.Fatalf("sampled commits not strictly increasing at %d", i)
		}
	}
}

func TestSampleZeroMaxMeansAll(t *testing.T) {
	c := commitsN(5)
	if got := Sample(c, 0); len(got) != 5 {
		t.Fatalf("got %d commits, want 5", len(got))
	}
}

func TestSampleSingleFrameIsLatest(t *testing.T) {
	c := commitsN(5)
	got := Sample(c, 1)
	if len(got) != 1 || got[0] != c[4] {
		t.Fatalf("Sample(c, 1) = %v, want just the last commit", got)
	}
}

// buildTestRepo creates a git repo with one commit containing a hand-written
// Go file, a path-detected generated file (.pb.go), and a content-detected
// generated file (mockery header).
func buildTestRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	files := map[string]string{
		"main.go":        "package main\n\nfunc main() {\n\tprintln(\"hi\")\n}\n",
		"api.pb.go":      "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\n\nfunc Marshal() {}\n",
		"client_mock.go": "// Code generated by mockery v2.20.0. DO NOT EDIT.\npackage main\n\nfunc MockClient() {}\n",
	}
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	for _, args := range [][]string{
		{"init", "-q"},
		{"-c", "user.name=t", "-c", "user.email=t@t", "add", "."},
		{"-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", "init"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
	return dir
}

func lastFrame(t *testing.T, dir string, opts Options) Frame {
	t.Helper()
	commits, err := history.Commits(context.Background(), dir, true)
	if err != nil {
		t.Fatal(err)
	}
	frames, err := Run(context.Background(), dir, commits, opts)
	if err != nil {
		t.Fatal(err)
	}
	var last Frame
	for f := range frames {
		if f.Err != nil {
			t.Fatalf("frame %d: %v", f.Index, f.Err)
		}
		last = f
	}
	return last
}

func TestRunSkipsGeneratedByDefault(t *testing.T) {
	dir := buildTestRepo(t)

	got := lastFrame(t, dir, Defaults())
	if got.Files != 1 {
		t.Errorf("default options: Files = %d, want 1 (generated files skipped)", got.Files)
	}

	opts := Defaults()
	opts.IncludeGenerated = true
	got = lastFrame(t, dir, opts)
	if got.Files != 3 {
		t.Errorf("IncludeGenerated: Files = %d, want 3", got.Files)
	}
}
